name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.11.*
  - jupyter
  - scikit-learn
  - scipy
  - pandas
  - numpy
  - matplotlib
  - tqdm
  - xgboost
  - pip:
      - ibm-db==3.1.4
      - coplin-db2
